Add support for DIR caches to cont-renew-notify
Previously, running cont-renew-notify would renew only the primary principal in
a DIR cache. This adds support for finding all caches in a collection and
renewing each of them.

Also add a help message, do some minor refactoring, etc..

diff --git a/cont-renew-notify b/cont-renew-notify
--- a/cont-renew-notify
+++ b/cont-renew-notify
@@ -14,6 +14,33 @@
 #command=`basename $0`
 #kill `pgrep -u $USER -f "$command" | grep -v $$` > /dev/null 2> /dev/null
 
+contained() {
+    if echo "$2" | grep "$1" >/dev/null 2>/dev/null; then
+        return 0 # true
+    else
+        return 1
+    fi
+}
+
+usage="Usage: $0 [-d|-f]"
+allcaches=false
+if contained "^DIR:/" "$KRB5CCNAME"; then
+    # We have a DIR: cache. Assume we should renew everything
+    allcaches=true
+fi
+while getopts "fdh" options; do
+    case $options in
+        f ) allcaches=false;;
+        d ) allcaches=true;;
+        h ) echo "$usage"; exit 0;;
+        \? ) echo "$usage"
+            exit 1;;
+        * ) echo "$usage"
+            exit 1;;
+    esac
+done
+shift `expr $OPTIND - 1`
+
 # Default to zephyring.
 if [ "x$ZEPHYR_SCREEN_NOTIFY" = "x" ]; then
     ZEPHYR_SCREEN_NOTIFY='zwrite -n "${ATHENA_USER:-$USER}"'
@@ -40,46 +67,95 @@ fi
 # fail at least once before succeeding on a subsequent notification.
 sleep 7
 
-while [ 1 ]; do
-    echo "Renewing at `$date`"
-    kinit -R
-    hash krb524init > /dev/null 2>&1 && krb524init
+notify_user()
+{
+    message="$1"
+
+    notifystatus="-1"
+    notifytries=0
+
+    # Notify user.  If notification is not successful, retry every
+    # 15 seconds up to 7 tries.  This may occur if
+    # cont-renew-notify is started before barnowl and barnowl is
+    # taking a long time to load.
+    while [ "$notifystatus" -ne "0" -a "$notifytries" -lt "7" ]; do
+        $echo "$message" | eval "$ZEPHYR_SCREEN_NOTIFY"
+        notifystatus=$?
+        if [ "$notifystatus" -ne "0" ]; then
+            tries=`expr $tries + 1`
+            sleep 15
+        fi
+    done
+}
+
+renew_cache()
+{
+    ccache_name=$1
+
+    echo "Renewing '$ccache_name'"
+    kinit -R -c "$ccache_name"
     sleep 1
-    aklog
-    zctl load > /dev/null 2> /dev/null
   
-    expirestr=`LC_TIME=C klist | grep 'renew until' | sed -e 's/[\t ]*renew until //' | head -n1`
+    expirestr=`LC_TIME=C klist -c "$ccache_name" | grep 'renew until' | sed -e 's/[\t ]*renew until //' | head -n1`
+    principal=`klist -c "$ccache_name" | grep 'Default principal:' | sed -e 's/Default principal: \(.*\)$/\1/'`
 
     if [ -z "$expirestr" ]; then
 	expire=0
-	message="You do not have renewable tickets on `hostname`.\nRun \"kinit -l7d\" to get renewable tickets."
+	message="You do not have renewable tickets for $principal on `hostname`.\nRun \"kinit -l7d\" to get renewable tickets.\n"
     else
 	expire=`$date -d "$expirestr" +%s`
 	
-	message="Your tickets on `hostname` will expire within the next 24 hours.\nRun \"kinit -l7d\" to get new renewable tickets."
+	message="Your tickets for $principal on `hostname` will expire within the next 24 hours.\nRun \"kinit -l7d\" to get new renewable tickets."
     fi
 
     # Non-renewable tickets will result in a negative difference.
     now=`$date +%s`
     difference=`expr $expire - $now`
-    if [ "$difference" -lt "86400" -a "$notified" != "$expire" ]; then
-	notifystatus="-1"
-	notifytries=0
+    if [ "$difference" -lt "86400" ]; then
+        # There's a problem
+	problems_new="$problems_new $expire-$ccache_name "
 
-	# Notify user.  If notification is not successful, retry every
-	# 15 seconds up to 7 tries.  This may occur if
-	# cont-renew-notify is started before barnowl and barnowl is
-	# taking a long time to load.
-	while [ "$notifystatus" -ne "0" -a "$notifytries" -lt "7" ]; do
-	    $echo "$message" | eval "$ZEPHYR_SCREEN_NOTIFY"
-	    notifystatus=$?
-	    if [ "$notifystatus" -ne "0" ]; then
-		tries=`expr $tries + 1`
-		sleep 15
-	    fi
-	done
-	notified=$expire
+        # Check if we knew about this last cycle
+        if contained " $expire-$ccache_name " "$problems"; then
+            true
+        else
+            notify_user "$message"
+        fi
     fi
+}
+
+if contained " " "$KRB5CCNAME"; then
+    # KRB5CCNAME contains a space. This may interfere with the parsing of
+    # "klist -l". However, it likely won't interfere with normal clients,
+    # like for example the zwrite we use below to warn about this
+    # situation.
+
+    message="Warning: your KRB5CCNAME on `hostname` contains whitespace.\nThis may break cont-renew-notify."
+    notify_user "$message"
+fi
+
+problems=" "
+while [ 1 ]; do
+    echo
+    echo "Renewing at `$date`"
+    problems_new=" "
+    if [ "$allcaches" = "true" ]; then
+        caches=`klist -l | awk 'NR > 2 { print $2 }'`
+        for cache in $caches; do
+            renew_cache "$cache";
+        done
+    else
+        renew_cache "$KRB5CCNAME"
+    fi
+    problems=$problems_new
+
+    # ccache_name is interesting only for DIR caches. krb524init is only
+    # interesting for machines that support krb4. I believe these don't
+    # overlap at all, so I don't feel too bad about not handling multiple
+    # sets of krb4 caches.
+    hash krb524init > /dev/null 2>&1 && krb524init
+    aklog
+    zctl load > /dev/null 2> /dev/null
   
     sleep 3600
 done
